export default {
  pages: [
    'pages/login/index',
    'pages/jobs/index',
    'pages/notifications/index',
    'pages/talent-search/index',
    'pages/profile/index',
    'pages/job-detail/index',
    'pages/chat-conversation/index',
    'pages/applications/index',
    'pages/enterprise-jobs/index',
    'pages/post-job/index',
    'pages/my-favorites/index',
    'pages/my-matches/index',
    'pages/match-results/index',
    'pages/talent-detail/index',
    'pages/enterprise-detail/index',
    'pages/edit-talent-profile/index',
    'pages/edit-enterprise-profile/index',
    'pages/reset-password/index',
    'pages/supply/index',
    'pages/supply/category/index',
    'pages/supply/company-detail/index',
    'pages/supply/apply/index',
    'pages/supply/my/index',
    'pages/share/index',
    'pages/share/detail/index',
    'pages/share/create/index',
    'pages/share/my/index',
    'pages/admin/index',
  ],
  window: {
    // 对齐网页版：无系统导航栏，页面自带白色返回头 / sticky 头
    navigationStyle: 'custom',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '餐猎',
    navigationBarTextStyle: 'black',
    // 窗口底色 = 页面灰底，避免下拉/回弹时露出默认白色
    backgroundColor: '#F7F8FA',
    backgroundColorTop: '#F7F8FA',
    backgroundColorBottom: '#F7F8FA',
  },
}
